language: minimal
if: branch = master

before_install:
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
#  - helm init --client-only

script:
  - mkdir files-to-gh-pages
  - echo $(pwd)
  - |
    for chart in $(find . -maxdepth 1 -type d ! -path . ! -path .git); do
      echo "Packaging chart $(basename ${chart})"
      helm package $(basename ${chart}) -d files-to-gh-pages
    done
  - cp README.md files-to-gh-pages
  - cd files-to-gh-pages
  - helm repo index .
  - ls -ltr 
  
deploy:
  provider: pages  
  github_token: $GITHUB_TOKEN
  local_dir: files-to-gh-pages
  target_branch: gh-pages
  verbose: true
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
