apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gomp.fullname" . }}
  labels:
    {{- include "gomp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
  postgresql-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- end }}
  {{- if not .Values.gomp.existingSecret }}
  secure-key: {{ .Values.gomp.secureKey | b64enc | quote }}
  {{- if .Values.gomp.aws.auth.accessKeyId }}
  aws-access-key-id: {{ .Values.gomp.aws.auth.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.gomp.aws.auth.secretAccessKey }}
  aws-secret-access-key: {{ .Values.gomp.aws.auth.secretAccessKey | b64enc | quote }}
  {{- end }}
  {{- end }}
