apiVersion: v2
name: gomp
description: Web-based recipe book
type: application
version: "1.0.5"
appVersion: "3.8.1"
dependencies:
  - name: postgresql
    version: "11.9.13"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
sources:
  - https://github.com/chadweimer/gomp
  - https://github.com/users/chadweimer/packages/container/package/aws-cli
  - https://github.com/users/chadweimer/packages/container/package/gomp
  - https://github.com/users/chadweimer/packages/container/package/pgsql-s3-backup
